//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Project = $ModelResult<$Schema, "Project">;
export type ProjectMember = $ModelResult<$Schema, "ProjectMember">;
export type UserStory = $ModelResult<$Schema, "UserStory">;
export type Sprint = $ModelResult<$Schema, "Sprint">;
export type Task = $ModelResult<$Schema, "Task">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
